name: telegram-bot-api

services:
    telegram-bot-api:
        image: aiogram/telegram-bot-api:latest
        env_file:
            - path: ../.env
              required: true
        environment:
            - TELEGRAM_LOCAL=True
        volumes:
            - ./telegram-bot-api-data:/var/lib/telegram-bot-api
        ports:
            - "8081:8081"

volumes:
    telegram-bot-api-data:
