name: Stable Release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: contains(github.event.head_commit.message, 'chore: bump version to')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from commit message
        id: extract-version
        run: |
          echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=chore: bump version to )\S+' > version.txt
          VERSION=$(cat version.txt)
          echo "::set-output name=version::$VERSION"

      - name: Tag the version
        run: |
          git tag ${{ steps.extract-version.outputs.version }}
          git push origin ${{ steps.extract-version.outputs.version }}

      - name: Create Stable Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract-version.outputs.version }}
          name: "${{ steps.extract-version.outputs.version }}"
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
